const conteudos = [
    // --- FILMES ---
    {
        id: "jurassic-world-recomeco",
        titulo: "Jurassic World: Recomeço",
        ano: 2025,
        genero: "Ação",
        tipo: "filme",
        categoria: "acao",
        poster: "images/jurassic-world-recomeco.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Uma expedição brava regiões equatoriais isoladas para extrair DNA de três criaturas pré-históricas massivas para uma descoberta médica inovadora.",
        videoUrl: "https://playerflixapi.com/filme/tt31036941",
        trailerUrl: "https://www.youtube.com/embed/ccuMLmZRd5g?autoplay=1",
        elenco: ["Chris Pratt", "Bryce Dallas Howard", "Sam Neill"],
        duracao: "2h 15m",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "Full HD",
        popularidade: 7.0
    },
    {
        id: "quarteto-fantastico-primeiros-passos",
        titulo: "Quarteto Fantástico: Primeiros Passos",
        ano: 2025,
        genero: "Super-Herói",
        tipo: "filme",
        categoria: "marvel",
        poster: "images/quarteto-fantastico-primeiros-passos.jpg",
        banner: "images/banner-filme-marvel.jpg",
        sinopse: "Ambientado em um mundo retro-futurista dos anos 1960, a Primeira Família da Marvel deve defender a Terra de uma divindade espacial faminta chamada Galactus.",
        videoUrl: "https://playerflixapi.com/filme/tt10676052",
        trailerUrl: "https://www.youtube.com/embed/CcSIvhDlYWw?autoplay=1",
        elenco: ["Pedro Pascal", "Vanessa Kirby", "Joseph Quinn"],
        duracao: "2h 0m",
        classificacao: "10",
        classificacaoNum: 10,
        qualidade: "HD",
        popularidade: 8.5
    },
    {
        id: "superman",
        titulo: "Superman",
        ano: 2025,
        genero: "Super-Herói",
        tipo: "filme",
        categoria: "dc",
        poster: "images/superman.jpg",
        banner: "images/banner-filme-dc.jpg",
        sinopse: "Superman tenta conciliar sua herança alienígena kryptoniana com sua criação humana como Clark Kent em Smallville, Kansas.",
        videoUrl: "https://playerflixapi.com/filme/tt5950044",
        trailerUrl: "https://www.youtube.com/watch?v=mjZgf6-ifCA",
        elenco: ["David Corenswet", "Rachel Brosnahan", "Nicholas Hoult"],
        duracao: "2h 20m",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "Full HD",
        popularidade: 9.0
    },
    {
        id: "homem-formiga-quantumania",
        titulo: "Homem-Formiga e a Vespa: Quantumania",
        ano: 2023,
        genero: "Super-Herói",
        tipo: "filme",
        categoria: "marvel",
        poster: "images/homem-formiga-quantumania.jpg",
        banner: "images/banner-filme-marvel.jpg",
        sinopse: "Scott Lang e Hope Van Dyne são arrastados para o Reino Quântico, onde devem enfrentar o vilão Kang, o Conquistador.",
        videoUrl: "https://playerflixapi.com/filme/tt10954600",
        trailerUrl: "https://www.youtube.com/watch?v=6jIz_8tokvg",
        elenco: ["Paul Rudd", "Evangeline Lilly", "Jonathan Majors"],
        duracao: "2h 5m",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "Full HD",
        popularidade: 6.1
    },
    {
        id: "resgate",
        titulo: "Resgate",
        ano: 2020,
        genero: "Ação",
        tipo: "filme",
        categoria: "acao",
        poster: "images/resgate.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Tyler Rake, um mercenário destemido, embarca na missão mais mortal de sua carreira ao ser contratado para resgatar o filho sequestrado de um senhor do crime.",
        videoUrl: "https://playerflixapi.com/filme/tt8936646",
        trailerUrl: "https://www.youtube.com/watch?v=GMKKq_bYd0E",
        elenco: ["Chris Hemsworth", "Rudhraksh Jaiswal", "Randeep Hooda"],
        duracao: "1h 56m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 6.8
    },
    {
        id: "o-esquadrao-suicida",
        titulo: "O Esquadrão Suicida",
        ano: 2021,
        genero: "Super-Herói",
        tipo: "filme",
        categoria: "dc",
        poster: "images/o-esquadrao-suicida.jpg",
        banner: "images/banner-filme-dc.jpg",
        sinopse: "Supervilões como Arlequina e Sanguinário juntam-se à Força Tarefa X em uma missão suicida na remota ilha de Corto Maltese.",
        videoUrl: "https://playerflixapi.com/filme/tt6334354",
        trailerUrl: "https://www.youtube.com/watch?v=h6bWwRCtg28",
        elenco: ["Margot Robbie", "Idris Elba", "John Cena"],
        duracao: "2h 12m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 7.2
    },
    {
        id: "premonicao-6",
        titulo: "Premonição 6: Laços de Sangue",
        ano: 2025,
        genero: "Suspense",
        tipo: "filme",
        categoria: "terror",
        poster: "images/premonicao-6.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Um novo grupo de jovens tenta enganar a Morte após uma premonição terrível, descobrindo que os laços familiares podem ser a chave para sobreviver.",
        videoUrl: "https://playerflixapi.com/filme/tt9619824",
        trailerUrl: "https://www.youtube.com/watch?v=x4xsMz-L4hk",
        elenco: ["Brec Bassinger", "Teo Briones", "Richard Harmon"],
        duracao: "1h 45m",
        classificacao: "18",
        classificacaoNum: 18,
        qualidade: "4K",
        popularidade: 7.5
    },
    {
        id: "fnaf-2",
        titulo: "Five Nights at Freddy’s 2",
        ano: 2025,
        genero: "Terror",
        tipo: "filme",
        categoria: "terror",
        poster: "images/fnaf-2.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Após os eventos do primeiro filme, novos segredos vêm à tona quando antigos animatrônicos retornam ainda mais perigosos. A Morte ronda o restaurante, e sobreviver até o amanhecer será mais difícil do que nunca.",
        videoUrl: "https://playerflixapi.com/filme/tt30274401",
        trailerUrl: "https://www.youtube.com/watch?v=fnaf2-trailer",
        elenco: ["Josh Hutcherson", "Matthew Lillard", "Elizabeth Lail"],
        duracao: "1h 45m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 8.4
    },
    {
        id: "karate-kid-lendas",
        titulo: "Karatê Kid: Lendas",
        ano: 2025,
        genero: "Ação",
        tipo: "filme",
        categoria: "acao",
        poster: "images/karate-kid-lendas.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Um jovem lutador de karatê descobre a história de seu mestre e a linhagem de lendas que o precederam.",
        videoUrl: "https://playerflixapi.com/filme/tt1674782",
        trailerUrl: "https://www.youtube.com/watch?v=jdZPKED0Dqg",
        elenco: ["Jackie Chan", "Ralph Macchio", "Ben Wang"],
        duracao: "1h 50m",
        classificacao: "10",
        classificacaoNum: 10,
        qualidade: "HD",
        popularidade: 8.2
    },
    {
        id: "deadpool-e-wolverine",
        titulo: "Deadpool e Wolverine",
        ano: 2024,
        genero: "Super-Herói",
        tipo: "filme",
        categoria: "marvel",
        poster: "images/deadpool-e-wolverine.jpg",
        banner: "images/banner-filme-marvel.jpg",
        sinopse: "Wade Wilson é recrutado pela Autoridade de Variação Temporal para salvar o multiverso, unindo forças com um Wolverine relutante.",
        videoUrl: "https://playerflixapi.com/filme/tt6263850",
        trailerUrl: "https://www.youtube.com/watch?v=dEbe0rS4Z2A",
        elenco: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin"],
        duracao: "2h 7m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 7.7
    },
    {
        id: "harry-potter-e-a-pedra-filosofal",
        titulo: "Harry Potter e a Pedra Filosofal",
        ano: 2001,
        genero: "Fantasia",
        tipo: "filme",
        categoria: "fantasia",
        poster: "images/harry-potter-e-a-pedra-filosofal.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Um menino órfão descobre em seu aniversário de onze anos que é um bruxo e possui poderes mágicos únicos.",
        videoUrl: "https://playerflixapi.com/filme/tt0241527",
        trailerUrl: "https://www.youtube.com/watch?v=VyHV0BRtdxo",
        elenco: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
        duracao: "2h 32m",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 7.6
    },
    {
        id: "guerra-mundial-z",
        titulo: "Guerra Mundial Z",
        ano: 2013,
        genero: "Terror",
        tipo: "filme",
        categoria: "terror",
        poster: "images/guerra-mundial-z.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Um ex-investigador da ONU viaja pelo mundo em uma corrida contra o tempo para deter uma pandemia zumbi que está derrubando exércitos e governos.",
        videoUrl: "https://playerflixapi.com/filme/tt0816711",
        trailerUrl: "https://www.youtube.com/watch?v=pGRvZfRY0_M",
        elenco: ["Brad Pitt", "Mireille Enos", "Daniella Kertesz"],
        duracao: "1h 56m",
        classificacao: "14",
        classificacaoNum: 14,
        qualidade: "Full HD",
        popularidade: 7.0
    },
    {
        id: "telefone-preto-1",
        titulo: "O Telefone Preto 1",
        ano: 2021,
        genero: "Terror",
        tipo: "filme",
        categoria: "terror",
        poster: "images/telefone-preto-1.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Um garoto de 13 anos, sequestrado por um assassino sádico, começa a receber chamadas de um telefone preto desconectado das vítimas anteriores do assassino.",
        videoUrl: "https://playerflixapi.com/filme/tt7144666",
        trailerUrl: "https://www.youtube.com/watch?v=dCAbPQnFAU4",
        elenco: ["Ethan Hawke", "Mason Thames", "Madeleine McGraw"],
        duracao: "1h 42m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 6.9
    },
    {
        id: "telefone-preto-2",
        titulo: "O Telefone Preto 2",
        ano: 2025,
        genero: "Terror",
        tipo: "filme",
        categoria: "terror",
        poster: "images/telefone-preto-2.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "A sequência do sucesso de terror, onde o mistério do telefone preto continua a assombrar novas vítimas.",
        videoUrl: "https://playerflixapi.com/filme/tt10954600",
        trailerUrl: "https://www.youtube.com/watch?v=dCAbPQnFAU4",
        elenco: ["Ethan Hawke", "Mason Thames"],
        duracao: "1h 45m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 8.0
    },
    {
        id: "sorria-2",
        titulo: "Sorria 2",
        ano: 2024,
        genero: "Terror",
        tipo: "filme",
        categoria: "terror",
        poster: "images/sorria-2.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "A maldição do sorriso retorna, perseguindo uma nova protagonista em um pesadelo psicológico sem fim.",
        videoUrl: "https://playerflixapi.com/filme/tt29268110",
        trailerUrl: "https://www.youtube.com/watch?v=07s2V_S9S9M",
        elenco: ["Naomi Scott", "Lukas Gage"],
        duracao: "2h 1m",
        classificacao: "18",
        classificacaoNum: 18,
        qualidade: "4K",
        popularidade: 7.8
    },
    {
        id: "mufasa-o-rei-leao",
        titulo: "Mufasa: O Rei Leão",
        ano: 2024,
        genero: "Aventura",
        tipo: "filme",
        categoria: "disney",
        poster: "images/mufasa-o-rei-leao.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "A história de origem de Mufasa, mostrando sua jornada de um filhote órfão até se tornar o grande rei das Terras do Reino.",
        videoUrl: "https://playerflixapi.com/filme/tt13186482",
        trailerUrl: "https://www.youtube.com/watch?v=o17MF9Wgg_E",
        elenco: ["Aaron Pierre", "Kelvin Harrison Jr."],
        duracao: "1h 58m",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "4K",
        popularidade: 8.5
    },
    {
        id: "sonic-3",
        titulo: "Sonic 3: O Filme",
        ano: 2024,
        genero: "Aventura",
        tipo: "filme",
        categoria: "acao",
        poster: "images/sonic-3.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Sonic, Tails e Knuckles devem enfrentar um novo e poderoso adversário: Shadow, o Ouriço.",
        videoUrl: "https://playerflixapi.com/filme/tt18259086",
        trailerUrl: "https://www.youtube.com/watch?v=qSu6i2iFKn0",
        elenco: ["Ben Schwartz", "Jim Carrey", "Keanu Reeves"],
        duracao: "1h 50m",
        classificacao: "10",
        classificacaoNum: 10,
        qualidade: "4K",
        popularidade: 8.8
    },
    {
        id: "moana-2",
        titulo: "Moana 2",
        ano: 2024,
        genero: "Aventura",
        tipo: "filme",
        categoria: "disney",
        poster: "images/moana-2.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Moana e Maui embarcam em uma nova e vasta jornada ao lado de uma tripulação de marinheiros improváveis.",
        videoUrl: "https://playerflixapi.com/filme/tt13622970",
        trailerUrl: "https://www.youtube.com/watch?v=h6bWwRCtg28",
        elenco: ["Auli'i Cravalho", "Dwayne Johnson"],
        duracao: "1h 40m",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "4K",
        popularidade: 8.2
    },
    {
        id: "venom-a-ultima-rodada",
        titulo: "Venom: A Última Rodada",
        ano: 2024,
        genero: "Ação",
        tipo: "filme",
        categoria: "marvel",
        poster: "images/venom-a-ultima-rodada.jpg",
        banner: "images/banner-filme-marvel.jpg",
        sinopse: "Eddie e Venom estão em fuga. Caçados por seus dois mundos, a dupla é forçada a tomar uma decisão devastadora.",
        videoUrl: "https://playerflixapi.com/filme/tt16366836",
        trailerUrl: "https://www.youtube.com/watch?v=__2bjWbetD0",
        elenco: ["Tom Hardy", "Chiwetel Ejiofor"],
        duracao: "1h 49m",
        classificacao: "14",
        classificacaoNum: 14,
        qualidade: "4K",
        popularidade: 7.5
    },
    {
        id: "gladiador-2",
        titulo: "Gladiador 2",
        ano: 2024,
        genero: "Ação",
        tipo: "filme",
        categoria: "acao",
        poster: "images/gladiador-2.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Anos após testemunhar a morte de Maximus, Lucius é forçado a entrar no Coliseu para lutar pelo futuro de Roma.",
        videoUrl: "https://playerflixapi.com/filme/tt9218128",
        trailerUrl: "https://www.youtube.com/watch?v=4uH6f_mYv6k",
        elenco: ["Paul Mescal", "Pedro Pascal", "Denzel Washington"],
        duracao: "2h 28m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 8.1
    },
    {
        id: "coringa-delirio-a-dois",
        titulo: "Coringa: Delírio a Dois",
        ano: 2024,
        genero: "Drama",
        tipo: "filme",
        categoria: "dc",
        poster: "images/coringa-delirio-a-dois.jpg",
        banner: "images/banner-filme-dc.jpg",
        sinopse: "Arthur Fleck está institucionalizado em Arkham à espera de julgamento por seus crimes como Coringa, onde encontra o amor verdadeiro.",
        videoUrl: "https://playerflixapi.com/filme/tt11315808",
        trailerUrl: "https://www.youtube.com/watch?v=07s2V_S9S9M",
        elenco: ["Joaquin Phoenix", "Lady Gaga"],
        duracao: "2h 18m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 6.5
    },
    {
        id: "divertida-mente-2",
        titulo: "Divertida Mente 2",
        ano: 2024,
        genero: "Animação",
        tipo: "filme",
        categoria: "disney",
        poster: "images/divertida-mente-2.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Riley agora é uma adolescente e novas emoções como a Ansiedade começam a aparecer no Quartel-General.",
        videoUrl: "https://playerflixapi.com/filme/tt22022452",
        trailerUrl: "https://www.youtube.com/watch?v=L4D8G69_S8E",
        elenco: ["Amy Poehler", "Maya Hawke"],
        duracao: "1h 36m",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "4K",
        popularidade: 9.5
    },
    {
        id: "bad-boys-ate-o-fim",
        titulo: "Bad Boys: Até o Fim",
        ano: 2024,
        genero: "Ação",
        tipo: "filme",
        categoria: "acao",
        poster: "images/bad-boys-ate-o-fim.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Os detetives Mike Lowrey e Marcus Burnett tentam limpar o nome do falecido capitão Howard, acusado de corrupção.",
        videoUrl: "https://playerflixapi.com/filme/tt4919268",
        trailerUrl: "https://www.youtube.com/watch?v=h6bWwRCtg28",
        elenco: ["Will Smith", "Martin Lawrence"],
        duracao: "1h 55m",
        classificacao: "14",
        classificacaoNum: 14,
        qualidade: "4K",
        popularidade: 7.9
    },
    {
        id: "planeta-dos-macacos-o-reinado",
        titulo: "Planeta dos Macacos: O Reinado",
        ano: 2024,
        genero: "Ficção Científica",
        tipo: "filme",
        categoria: "acao",
        poster: "images/planeta-dos-macacos-o-reinado.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Muitos anos após o reinado de César, um jovem macaco embarca em uma jornada que o levará a questionar tudo o que lhe foi ensinado.",
        videoUrl: "https://playerflixapi.com/filme/tt11389872",
        trailerUrl: "https://www.youtube.com/watch?v=Kdr5oedn7q8",
        elenco: ["Owen Teague", "Freya Allan"],
        duracao: "2h 25m",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "4K",
        popularidade: 7.6
    },
    {
        id: "furiosa-uma-saga-mad-max",
        titulo: "Furiosa: Uma Saga Mad Max",
        ano: 2024,
        genero: "Ação",
        tipo: "filme",
        categoria: "acao",
        poster: "images/furiosa-uma-saga-mad-max.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "A jovem Furiosa é sequestrada do Lugar Verde de Muitas Mães e cai nas mãos de uma grande Horda de Motoqueiros liderada pelo Senhor da Guerra Dementus.",
        videoUrl: "https://playerflixapi.com/filme/tt12037194",
        trailerUrl: "https://www.youtube.com/watch?v=XJMuhwVlca4",
        elenco: ["Anya Taylor-Joy", "Chris Hemsworth"],
        duracao: "2h 28m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 7.8
    },
    {
        id: "duna-parte-2",
        titulo: "Duna: Parte 2",
        ano: 2024,
        genero: "Ficção Científica",
        tipo: "filme",
        categoria: "acao",
        poster: "images/duna-parte-2.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Paul Atreides se une a Chani e aos Fremen em uma guerra de vingança contra os conspiradores que destruíram sua família.",
        videoUrl: "https://playerflixapi.com/filme/tt15239678",
        trailerUrl: "https://www.youtube.com/watch?v=U2Qp5pL3ovA",
        elenco: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
        duracao: "2h 46m",
        classificacao: "14",
        classificacaoNum: 14,
        qualidade: "4K",
        popularidade: 9.1
    },
    {
        id: "kung-fu-panda-4",
        titulo: "Kung Fu Panda 4",
        ano: 2024,
        genero: "Animação",
        tipo: "filme",
        categoria: "acao",
        poster: "images/kung-fu-panda-4.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Po é escolhido para se tornar o Líder Espiritual do Vale da Paz e deve treinar um novo Dragão Guerreiro enquanto enfrenta uma feiticeira perversa.",
        videoUrl: "https://playerflixapi.com/filme/tt21692408",
        trailerUrl: "https://www.youtube.com/watch?v=l6_h_m_m_m_m",
        elenco: ["Jack Black", "Awkwafina"],
        duracao: "1h 34m",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "4K",
        popularidade: 7.4
    },
    {
        id: "se-nao-fosse-voce",
        titulo: "Se Não Fosse Você",
        ano: 2025,
        genero: "Romance",
        tipo: "filme",
        categoria: "romance",
        poster: "images/se-nao-fosse-voce.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Morgan Grant e sua filha adolescente, Clara, desejam apenas não ser parecidas uma com a outra. Enquanto Morgan engravidou muito jovem e abdicou dos próprios sonhos, Clara quer trilhar um caminho diferente. A convivência, já conflituosa, torna-se insustentável após um trágico acidente revelar traições e segredos que abalam as estruturas da família, forçando ambas a se redescobrirem em meio ao luto.",
        videoUrl: "https://playerflixapi.com/filme/tt33088452",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        elenco: ["Mckenna Grace", "Mason Thames", "Dave Franco"],
        duracao: "1h 57m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "HD",
        popularidade: 6.3
    },
    {
        id: "101-dalmatas",
        titulo: "101 Dálmatas",
        ano: 1961,
        genero: "Aventura",
        tipo: "filme",
        categoria: "disney",
        poster: "images/101-dalmatas.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Pongo e Prenda devem resgatar seus filhotes dálmatas da vilã Cruella De Vil, que quer transformá-los em casacos de pele.",
        videoUrl: "https://playerflixapi.com/filme/tt0055254",
        trailerUrl: "https://www.youtube.com/watch?v=RNg7vtbaC3Y",
        elenco: ["Rod Taylor", "Cate Bauer"],
        duracao: "1h 19m",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 8.1
    },
    {
        id: "nerve",
        titulo: "Nerve: Um Jogo Sem Regras",
        ano: 2016,
        genero: "Ação",
        tipo: "filme",
        categoria: "acao",
        poster: "images/nerve.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Uma estudante entra em um jogo online de desafios extremos onde espectadores decidem até onde os jogadores devem ir, colocando sua vida em risco.",
        videoUrl: "https://playerflixapi.com/filme/tt3531824",
        trailerUrl: "https://www.youtube.com/watch?v=2PR9MOPTI7g",
        elenco: ["Emma Roberts", "Dave Franco"],
        duracao: "1h 36min",
        classificacao: "14",
        classificacaoNum: 14,
        qualidade: "Full HD",
        popularidade: 7.3
    },

    // --- SÉRIES ---
    {
        id: "pinguim",
        titulo: "Pinguim",
        ano: 2024,
        genero: "Crime",
        tipo: "serie",
        categoria: "dc",
        poster: "images/pinguim.jpg",
        banner: "images/banner-filme-dc.jpg",
        sinopse: "A ascensão de Oswald Cobblepot ao poder no submundo do crime de Gotham City após los eventos de 'The Batman'.",
        videoUrl: "https://playerflixapi.com/serie/194764",
        trailerUrl: "https://www.youtube.com/watch?v=sfM7_JLk-84",
        elenco: ["Colin Farrell", "Cristin Milioti"],
        duracao: "1 temporada",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 8.8
    },
    {
        id: "it-bem-vindos-a-derry",
        titulo: "It: Bem-vindos a Derry",
        ano: 2025,
        genero: "Terror",
        tipo: "serie",
        categoria: "terror",
        poster: "images/it-bem-vindos-a-derry.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Uma prequela dos filmes 'It', explorando a história de Pennywise e a cidade amaldiçoada de Derry.",
        videoUrl: "https://playerflixapi.com/serie/200875",
        trailerUrl: "https://www.youtube.com/watch?v=hdCIZK2zcYw",
        elenco: ["Bill Skarsgård", "Taylour Paige"],
        duracao: "1 temporada",
        classificacao: "18",
        classificacaoNum: 18,
        qualidade: "4K",
        popularidade: 9.0
    },
    {
        id: "grimm",
        titulo: "Grimm",
        ano: 2011,
        genero: "Drama",
        tipo: "serie",
        categoria: "drama",
        poster: "images/grimm.jfif",
        banner: "images/banner-filme.jpg",
        sinopse: "Um detetive descobre ser um Grimm, um guardião encarregado de manter o equilíbrio entre a humanidade e criaturas sobrenaturais conhecidas como Wesen.",
        videoUrl: "https://playerflixapi.com/serie/39351",
        trailerUrl: "https://www.youtube.com/watch?v=2JmXj0E4FJY",
        elenco: ["David Giuntoli", "Bitsie Tulloch", "Silas Weir Mitchell"],
        duracao: "6 temporadas",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "Full HD",
        popularidade: 8.7
    },
    {
        id: "sobrenatural",
        titulo: "Sobrenatural",
        ano: 2005,
        genero: "Terror",
        tipo: "serie",
        categoria: "terror",
        poster: "images/sobrenatural.jpg",
        banner: "images/banner-serie.jpg",
        sinopse: "Dois irmãos caçadores percorrem os Estados Unidos enfrentando demônios, fantasmas e entidades sobrenaturais enquanto tentam impedir o apocalipse.",
        videoUrl: "https://playerflixapi.com/serie/1622",
        trailerUrl: "https://www.youtube.com/watch?v=t-775JyzDTk",
        elenco: ["Jared Padalecki", "Jensen Ackles", "Misha Collins"],
        duracao: "15 temporadas",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "Full HD",
        popularidade: 9.2
    },
    {
        id: "stranger-things",
        titulo: "Stranger Things",
        ano: 2016,
        genero: "Suspense",
        tipo: "serie",
        categoria: "suspense",
        poster: "images/stranger-things.jpg",
        banner: "images/banner-serie.jpg",
        sinopse: "Após o desaparecimento de um garoto, um grupo de amigos descobre experimentos secretos, forças sobrenaturais e uma dimensão paralela que ameaça sua cidade.",
        videoUrl: "https://playerflixapi.com/serie/66732",
        trailerUrl: "https://www.youtube.com/watch?v=b9EkMc79ZSU",
        elenco: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
        duracao: "5 temporadas",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 9.4
    },
    {
        id: "pacificador",
        titulo: "Pacificador",
        ano: 2022,
        genero: "Ação",
        tipo: "serie",
        categoria: "dc",
        poster: "images/pacificador.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "A continuação da história do personagem de 'O Esquadrão Suicida', um homem que acredita na paz a qualquer custo.",
        videoUrl: "https://playerflixapi.com/serie/110492",
        trailerUrl: "https://www.youtube.com/watch?v=WHXq6tfzHK0",
        elenco: ["John Cena", "Danielle Brooks", "Freddie Stroma"],
        duracao: "2 temporadas",
        classificacao: "18",
        classificacaoNum: 18,
        qualidade: "4K",
        popularidade: 8.9
    },
    {
        id: "pll",
        titulo: "Pretty Little Liars",
        ano: 2010,
        genero: "Suspense",
        tipo: "serie",
        categoria: "suspense",
        poster: "images/pll.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Quatro amigas se unem contra um inimigo anônimo que ameaça revelar seus segredos mais sombrios.",
        videoUrl: "https://playerflixapi.com/serie/31917",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        elenco: ["Troian Bellisario", "Ashley Benson", "Lucy Hale"],
        duracao: "7 temporadas",
        classificacao: "14",
        classificacaoNum: 14,
        qualidade: "HD",
        popularidade: 8.4
    },
    {
        id: "voce",
        titulo: "Você",
        ano: 2018,
        genero: "Suspense",
        tipo: "serie",
        categoria: "suspense",
        poster: "images/voce.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Um gerente de livraria perigosamente charmoso fica obcecado por uma aspirante a escritora.",
        videoUrl: "https://playerflixapi.com/serie/78191",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        elenco: ["Penn Badgley", "Elizabeth Lail"],
        duracao: "5 temporadas",
        classificacao: "18",
        classificacaoNum: 18,
        qualidade: "Full HD",
        popularidade: 9.2
    },
    {
        id: "magnum",
        titulo: "Magnum",
        ano: 2026,
        genero: "Ação, Comédia, Drama",
        tipo: "serie",
        categoria: "super-herói",
        poster: "images/magnum.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Simon Williams é um ator talentoso cuja vida muda radicalmente quando descobre que possui habilidades extraordinárias enquanto tenta alcançar o estrelato em Hollywood.",
        videoUrl: "https://playerflixapi.com/serie/198178",
        trailerUrl: "https://www.youtube.com/embed/jljXyJfiRDQ?si=k1a-BZj-lxnLvlW8",
        elenco: ["Yahya Abdul-Mateen II", "Ben Kingsley"],
        duracao: "1 temporada",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "4K UHD",
        popularidade: 9.0
    },

    // --- DESENHOS / CARTOON ---
    {
        id: "hora-de-aventura",
        titulo: "Hora de Aventura",
        ano: 2010,
        genero: "Aventura",
        tipo: "serie",
        categoria: "cartoon",
        poster: "images/hora-de-aventura.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Um garoto humano chamado Finn e seu melhor amigo, o cão mágico Jake, vivem grandes aventuras na Terra de Ooo.",
        videoUrl: "https://playerflixapi.com/serie/15260",
        trailerUrl: "https://www.youtube.com/watch?v=51laYl7spBI",
        elenco: ["Jeremy Shada", "John DiMaggio"],
        duracao: "10 temporadas",
        classificacao: "10",
        classificacaoNum: 10,
        qualidade: "HD",
        popularidade: 9.3
    },
    {
        id: "apenas-um-show",
        titulo: "Apenas um Show",
        ano: 2010,
        genero: "Comédia",
        tipo: "serie",
        categoria: "cartoon",
        poster: "images/apenas-um-show.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "As aventuras surreais de dois zeladores, um gaio-azul chamado Mordecai e um guaxinim chamado Rigby.",
        videoUrl: "https://playerflixapi.com/serie/31132",
        trailerUrl: "https://www.youtube.com/watch?v=FhKIg8O4AWI",
        elenco: ["J.G. Quintel", "William Salyers", "Sam Marin"],
        duracao: "8 temporadas",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 8.5
    },
    {
        id: "o-incrivel-mundo-de-gumball",
        titulo: "O Incrível Mundo de Gumball",
        ano: 2011,
        genero: "Comédia",
        tipo: "serie",
        categoria: "cartoon",
        poster: "images/o-incrivel-mundo-de-gumball.webp",
        banner: "images/banner-filme.jpg",
        sinopse: "As desventuras de Gumball Watterson, um gato azul de 12 anos, e seu irmão adotivo, Darwin, um peixe-dourado.",
        videoUrl: "https://playerflixapi.com/serie/37606",
        trailerUrl: "https://www.youtube.com/watch?v=On_IHVGEU6E",
        elenco: ["Logan Grove", "Kwesi Boakye", "Teresa Gallagher"],
        duracao: "6 temporadas",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 8.7
    },
    {
        id: "steven-universo",
        titulo: "Steven Universo",
        ano: 2013,
        genero: "Fantasia",
        tipo: "serie",
        categoria: "cartoon",
        poster: "images/steven-universo.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Steven, um garoto meio humano, meio Gem, aprende a usar seus poderes para proteger o mundo com as Crystal Gems.",
        videoUrl: "https://playerflixapi.com/serie/61175",
        trailerUrl: "https://www.youtube.com/watch?v=On_IHVGEU6E",
        elenco: ["Zach Callison", "Estelle", "Michaela Dietz"],
        duracao: "5 temporadas",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 8.6
    },
    {
        id: "o-incrivel-circo-digital",
        titulo: "O Incrível Circo Digital",
        ano: 2023,
        genero: "Comédia",
        tipo: "serie",
        categoria: "serie",
        poster: "images/o-incrivel-circo-digital.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Uma mulher fica presa em um mundo digital bizarro junto com outros humanos, todos transformados em personagens de desenho animado.",
        videoUrl: "https://playerflixapi.com/serie/261145",
        trailerUrl: "https://www.youtube.com/watch?v=ned09SQH23s",
        elenco: ["Lizzie Freeman", "Alex Rochon"],
        duracao: "1 temporada",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "HD",
        popularidade: 9.6
    },

    // --- ANIMES ---
    {
        id: "one-piece",
        titulo: "One Piece",
        ano: 1999,
        genero: "Aventura",
        tipo: "anime",
        categoria: "anime",
        poster: "images/one-piece.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Monkey D. Luffy e sua tripulação pirata exploram um mundo fantástico de oceanos infinitos e ilhas exóticas em busca do tesouro supremo.",
        videoUrl: "https://playerflixapi.com/serie/37854",
        trailerUrl: "https://www.youtube.com/watch?v=YC8SLpnxsL4",
        elenco: ["Mayumi Tanaka", "Kazuya Nakai", "Akemi Okamura"],
        duracao: "Mais de 1000 episódios",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "Full HD",
        popularidade: 9.0
    },
    {
        id: "naruto",
        titulo: "Naruto",
        ano: 2002,
        genero: "Aventura",
        tipo: "anime",
        categoria: "anime",
        poster: "images/naruto.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Naruto Uzumaki, um ninja adolescente barulhento, busca reconhecimento e sonha em se tornar o Hokage, o líder de sua vila.",
        videoUrl: "https://playerflixapi.com/serie/46260",
        trailerUrl: "https://www.youtube.com/watch?v=fR28U_Xovk4",
        elenco: ["Junko Takeuchi", "Chie Nakamura", "Noriaki Sugiyama"],
        duracao: "220 episódios",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "Full HD",
        popularidade: 8.4
    },
    {
        id: "haikyu",
        titulo: "Haikyu!!",
        ano: 2014,
        genero: "Esporte",
        tipo: "anime",
        categoria: "anime",
        poster: "images/haikyu!!.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "Shoyo Hinata, um garoto de baixa estatura, se junta ao time de vôlei da escola para se tornar um grande jogador.",
        videoUrl: "https://playerflixapi.com/serie/60863",
        trailerUrl: "https://www.youtube.com/watch?v=6QBiUaO3tL8",
        elenco: ["Ayumu Murase", "Kaito Ishikawa", "Yu Hayashi"],
        duracao: "4 temporadas",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 8.9
    },
    {
        id: "jojo-bizarre-adventure",
        titulo: "Jojo's Bizarre Adventure",
        ano: 2012,
        genero: "Ação",
        tipo: "anime",
        categoria: "anime",
        poster: "images/jojo-bizarre-adventure.jpg",
        banner: "images/banner-filme.jpg",
        sinopse: "A saga da família Joestar e suas batalhas contra forças sobrenaturais através das gerações.",
        videoUrl: "https://playerflixapi.com/serie/45790",
        trailerUrl: "https://www.youtube.com/watch?v=NyGZT2AgB4s",
        elenco: ["Daisuke Ono", "Unshō Ishizuka"],
        duracao: "6 partes",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "Full HD",
        popularidade: 9.4
    }
];