const conteudos = [
    // --- FILMES ---
    {
        id: "jurassic-world-recomeco",
        titulo: "Jurassic World: Recomeço",
        ano: 2025,
        genero: "Ação",
        tipo: "filme",
        categoria: "acao",
        poster: "../images/posters/jurassic-world-recomeco.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Uma expedição brava regiões equatoriais isoladas para extrair DNA de três criaturas pré-históricas massivas para uma descoberta médica inovadora.",
        videoUrl: "https://playerflixapi.com/filme/tt31036941",
        trailerUrl: "https://www.youtube.com/watch?v=klUD5EEKujI",
        detalhesUrl: "detalhes-jurassic-world-recomeco.html",
        elenco: ["Chris Pratt", "Bryce Dallas Howard", "Sam Neill"],
        duracao: "2h 15m",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "Full HD",
        popularidade: 7.0
    },
    {
        id: "quarteto-fantastico-primeiros-passos",
        titulo: "Quarteto Fantástico: Primeiros Passos",
        ano: 2025,
        genero: "Super-Herói",
        tipo: "filme",
        categoria: "marvel",
        poster: "../images/posters/quarteto-fantastico-primeiros-passos.jpg",
        banner: "../images/banners/banner-filme-marvel.jpg",
        sinopse: "Ambientado em um mundo retro-futurista dos anos 1960, a Primeira Família da Marvel deve defender a Terra de uma divindade espacial faminta chamada Galactus.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/embed/CcSIvhDlYWw?autoplay=1",
        detalhesUrl: "detalhes-quarteto-fantastico-primeiros-passos.html",
        elenco: ["Pedro Pascal", "Vanessa Kirby", "Joseph Quinn"],
        duracao: "2h 0m",
        classificacao: "10",
        classificacaoNum: 10,
        qualidade: "HD",
        popularidade: 8.5
    },
    {
        id: "superman",
        titulo: "Superman",
        ano: 2025,
        genero: "Super-Herói",
        tipo: "filme",
        categoria: "dc",
        poster: "../images/posters/superman.jpg",
        banner: "../images/banners/banner-filme-dc.jpg",
        sinopse: "Superman tenta conciliar sua herança alienígena kryptoniana com sua criação humana como Clark Kent em Smallville, Kansas.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=mjZgf6-ifCA",
        detalhesUrl: "detalhes-superman.html",
        elenco: ["David Corenswet", "Rachel Brosnahan", "Nicholas Hoult"],
        duracao: "2h 20m",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "Full HD",
        popularidade: 9.0
    },
    {
        id: "homem-formiga-quantumania",
        titulo: "Homem-Formiga e a Vespa: Quantumania",
        ano: 2023,
        genero: "Super-Herói",
        tipo: "filme",
        categoria: "marvel",
        poster: "../images/posters/homem-formiga-quantumania.jpg",
        banner: "../images/banners/banner-filme-marvel.jpg",
        sinopse: "Scott Lang e Hope Van Dyne são arrastados para o Reino Quântico, onde devem enfrentar o vilão Kang, o Conquistador.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=6jIz_8tokvg",
        detalhesUrl: "detalhes-homem-formiga-quantumania.html",
        elenco: ["Paul Rudd", "Evangeline Lilly", "Jonathan Majors"],
        duracao: "2h 5m",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "Full HD",
        popularidade: 6.1
    },
    {
        id: "resgate",
        titulo: "Resgate",
        ano: 2020,
        genero: "Ação",
        tipo: "filme",
        categoria: "acao",
        poster: "../images/posters/resgate.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Tyler Rake, um mercenário destemido, embarca na missão mais mortal de sua carreira ao ser contratado para resgatar o filho sequestrado de um senhor do crime.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=GMKKq_bYd0E",
        detalhesUrl: "detalhes-resgate.html",
        elenco: ["Chris Hemsworth", "Rudhraksh Jaiswal", "Randeep Hooda"],
        duracao: "1h 56m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 6.8
    },
    {
        id: "o-esquadrao-suicida",
        titulo: "O Esquadrão Suicida",
        ano: 2021,
        genero: "Super-Herói",
        tipo: "filme",
        categoria: "dc",
        poster: "../images/posters/o-esquadrao-suicida.jpg",
        banner: "../images/banners/banner-filme-dc.jpg",
        sinopse: "Supervilões como Arlequina e Sanguinário juntam-se à Força Tarefa X em uma missão suicida na remota ilha de Corto Maltese.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=h6bWwRCtg28",
        detalhesUrl: "detalhes-o-esquadrao-suicida.html",
        elenco: ["Margot Robbie", "Idris Elba", "John Cena"],
        duracao: "2h 12m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 7.2
    },
    {
        id: "premonicao-6",
        titulo: "Premonição 6: Laços de Sangue",
        ano: 2025,
        genero: "Suspense",
        tipo: "filme",
        categoria: "terror",
        poster: "../images/posters/premonicao-6.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Um novo grupo de jovens tenta enganar a Morte após uma premonição terrível, descobrindo que os laços familiares podem ser a chave para sobreviver.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=x4xsMz-L4hk",
        detalhesUrl: "detalhes-premonicao-6.html",
        elenco: ["Brec Bassinger", "Teo Briones", "Richard Harmon"],
        duracao: "1h 45m",
        classificacao: "18",
        classificacaoNum: 18,
        qualidade: "4K",
        popularidade: 7.5
    },
    {
        id: "karate-kid-lendas",
        titulo: "Karatê Kid: Lendas",
        ano: 2025,
        genero: "Ação",
        tipo: "filme",
        categoria: "acao",
        poster: "../images/posters/karate-kid-lendas.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Um jovem lutador de karatê descobre a história de seu mestre e a linhagem de lendas que o precederam.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=jdZPKED0Dqg",
        detalhesUrl: "detalhes-karate-kid-lendas.html",
        elenco: ["Jackie Chan", "Ralph Macchio", "Ben Wang"],
        duracao: "1h 50m",
        classificacao: "10",
        classificacaoNum: 10,
        qualidade: "HD",
        popularidade: 8.2
    },
    {
        id: "deadpool-e-wolverine",
        titulo: "Deadpool e Wolverine",
        ano: 2024,
        genero: "Super-Herói",
        tipo: "filme",
        categoria: "marvel",
        poster: "../images/posters/deadpool-e-wolverine.jpg",
        banner: "../images/banners/banner-filme-marvel.jpg",
        sinopse: "Wade Wilson é recrutado pela Autoridade de Variação Temporal para salvar o multiverso, unindo forças com um Wolverine relutante.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=dEbe0rS4Z2A",
        detalhesUrl: "detalhes-deadpool-e-wolverine.html",
        elenco: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin"],
        duracao: "2h 7m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 7.7
    },
    {
        id: "harry-potter-e-a-pedra-filosofal",
        titulo: "Harry Potter e a Pedra Filosofal",
        ano: 2001,
        genero: "Fantasia",
        tipo: "filme",
        categoria: "fantasia",
        poster: "../images/posters/harry-potter-e-a-pedra-filosofal.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Um menino órfão descobre em seu aniversário de onze anos que é um bruxo e possui poderes mágicos únicos.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=VyHV0BRtdxo",
        detalhesUrl: "detalhes-harry-potter-e-a-pedra-filosofal.html",
        elenco: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
        duracao: "2h 32m",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 7.6
    },
    {
        id: "guerra-mundial-z",
        titulo: "Guerra Mundial Z",
        ano: 2013,
        genero: "Terror",
        tipo: "filme",
        categoria: "terror",
        poster: "../images/posters/guerra-mundial-z.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Um ex-investigador da ONU viaja pelo mundo em uma corrida contra o tempo para deter uma pandemia zumbi que está derrubando exércitos e governos.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=pGRvZfRY0_M",
        detalhesUrl: "detalhes-guerra-mundial-z.html",
        elenco: ["Brad Pitt", "Mireille Enos", "Daniella Kertesz"],
        duracao: "1h 56m",
        classificacao: "14",
        classificacaoNum: 14,
        qualidade: "Full HD",
        popularidade: 7.0
    },
    {
        id: "telefone-preto-1",
        titulo: "O Telefone Preto 1",
        ano: 2021,
        genero: "Terror",
        tipo: "filme",
        categoria: "terror",
        poster: "../images/posters/telefone-preto-1.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Um garoto de 13 anos, sequestrado por um assassino sádico, começa a receber chamadas de um telefone preto desconectado das vítimas anteriores do assassino.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=dCAbPQnFAU4",
        detalhesUrl: "detalhes-telefone-preto-1.html",
        elenco: ["Ethan Hawke", "Mason Thames", "Madeleine McGraw"],
        duracao: "1h 42m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 6.9
    },
    {
        id: "telefone-preto-2",
        titulo: "O Telefone Preto 2",
        ano: 2025,
        genero: "Terror",
        tipo: "filme",
        categoria: "terror",
        poster: "../images/posters/telefone-preto-2.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "A sequência do sucesso de terror, onde o telefone preto volta a tocar, trazendo novas e aterrorizantes mensagens do além.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=YLIxDkY4epQ",
        detalhesUrl: "detalhes-telefone-preto-2.html",
        elenco: ["Ethan Hawke", "Mason Thames", "Madeleine McGraw"],
        duracao: "1h 45m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 7.9
    },
    {
        id: "bailarina-do-universo-john-wick",
        titulo: "Bailarina: Do Universo John Wick",
        ano: 2025,
        genero: "Ação",
        tipo: "filme",
        categoria: "acao",
        poster: "../images/posters/bailarina-do-universo-john-wick.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Uma assassina treinada busca vingança contra aqueles que mataram sua família, entrando no submundo de John Wick.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=XdJgqI_PXjI",
        detalhesUrl: "detalhes-bailarina-do-universo-john-wick.html",
        elenco: ["Ana de Armas", "Keanu Reeves", "Ian McShane"],
        duracao: "1h 58m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 8.8
    },
    {
        id: "until-dawn",
        titulo: "Until Dawn: Noite de Terror",
        ano: 2025,
        genero: "Terror",
        tipo: "filme",
        categoria: "terror",
        poster: "../images/posters/until-dawn.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Oito amigos ficam presos em um chalé isolado na montanha, onde descobrem que não estão sozinhos e precisam sobreviver até o amanhecer.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        detalhesUrl: "detalhes-until-dawn.html",
        elenco: ["Ella Rubin", "Michael Cimino", "Odessa A'zion"],
        duracao: "1h 40m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 7.7
    },
    {
        id: "lilo-e-stitch-live-action",
        titulo: "Lilo & Stitch: Live Action",
        ano: 2025,
        genero: "Fantasia",
        tipo: "filme",
        categoria: "disney",
        poster: "../images/posters/lilo-e-stitch-live-action.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Uma releitura live-action do clássico animado da Disney sobre uma garota solitária que adota um alienígena fugitivo.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        detalhesUrl: "detalhes-lilo-e-stitch-live-action.html",
        elenco: ["Maia Kealoha", "Sydney Agudong", "Billy Magnussen"],
        duracao: "1h 50m",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 8.5
    },
    {
        id: "como-treinar-seu-dragao-live-action",
        titulo: "Como Treinar o Seu Dragão",
        ano: 2025,
        genero: "Fantasia",
        tipo: "filme",
        categoria: "fantasia",
        poster: "../images/posters/como-treinar-seu-dragao-live-action.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "A adaptação live-action da amada trilogia animada sobre a amizade improvável entre um jovem viking e um dragão temível.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        detalhesUrl: "detalhes-como-treinar-seu-dragao-live-action.html",
        elenco: ["Mason Thames", "Nico Parker", "Gerard Butler"],
        duracao: "2h 0m",
        classificacao: "10",
        classificacaoNum: 10,
        qualidade: "Full HD",
        popularidade: 9.0
    },
    {
        id: "m3gan-2-0",
        titulo: "M3GAN 2.0",
        ano: 2025,
        genero: "Terror",
        tipo: "filme",
        categoria: "terror",
        poster: "../images/posters/m3gan-2-0.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "A boneca assassina com inteligência artificial retorna para causar mais caos e terror tecnológico.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        detalhesUrl: "detalhes-m3gan-2-0.html",
        elenco: ["Allison Williams", "Violet McGraw"],
        duracao: "1h 45m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "4K",
        popularidade: 7.8
    },
    {
        id: "os-donos-do-jogo",
        titulo: "Os Donos do Jogo",
        ano: 2025,
        genero: "Suspense",
        tipo: "filme",
        categoria: "suspense",
        poster: "../images/posters/os-donos-do-jogo.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Um thriller de alta tensão sobre poder, corrupção e os segredos sombrios do mundo corporativo.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        detalhesUrl: "detalhes-os-donos-do-jogo.html",
        elenco: ["Elenco A", "Elenco B"],
        duracao: "2h 10m",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "Full HD",
        popularidade: 7.2
    },
    {
        id: "juntos-para-sempre",
        titulo: "Juntos Para Sempre",
        ano: 2025,
        genero: "Romance",
        tipo: "filme",
        categoria: "romance",
        poster: "../images/posters/juntos-para-sempre.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Uma história emocionante sobre amor, perda e a promessa de eternidade.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        detalhesUrl: "detalhes-juntos-para-sempre.html",
        elenco: ["Ator X", "Atriz Y"],
        duracao: "1h 55m",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "HD",
        popularidade: 7.0
    },

    // --- SÉRIES ---
    {
        id: "the-boys",
        titulo: "The Boys",
        ano: 2019,
        genero: "Super-Herói",
        tipo: "serie",
        categoria: "acao",
        poster: "../images/posters/the-boys.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Um grupo de vigilantes se propõe a derrubar super-heróis corruptos que abusam de seus superpoderes e da fama.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=I0RC15nmjpU",
        detalhesUrl: "detalhes-the-boys.html",
        elenco: ["Karl Urban", "Jack Quaid", "Antony Starr"],
        duracao: "4 temporadas",
        classificacao: "18",
        classificacaoNum: 18,
        qualidade: "4K",
        popularidade: 8.7
    },
    {
        id: "stranger-things",
        titulo: "Stranger Things",
        ano: 2016,
        genero: "Ficção Científica",
        tipo: "serie",
        categoria: "fantasia",
        poster: "../images/posters/stranger-things.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Quando um jovem desaparece, uma pequena cidade descobre um mistério envolvendo experimentos secretos, forças sobrenaturais e uma garotinha estranha.",
        videoUrl: "https://playerflixapi.com/serie/66732",
        trailerUrl: "https://www.youtube.com/watch?v=Wb3kaP580kA",
        detalhesUrl: "detalhes-stranger-things.html",
        elenco: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
        duracao: "4 temporadas",
        classificacao: "14",
        classificacaoNum: 14,
        qualidade: "Full HD",
        popularidade: 8.7
    },
    {
        id: "loki",
        titulo: "Loki",
        ano: 2021,
        genero: "Super-Herói",
        tipo: "serie",
        categoria: "marvel",
        poster: "../images/posters/loki.jpg",
        banner: "../images/banners/banner-filme-marvel.jpg",
        sinopse: "O Deus da Trapaça, Loki, é levado perante a Autoridade de Variação Temporal após roubar o Tesseract durante os eventos de Vingadores: Ultimato.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=xdBWrkcmMwU",
        detalhesUrl: "detalhes-loki.html",
        elenco: ["Tom Hiddleston", "Sophia Di Martino", "Owen Wilson"],
        duracao: "2 temporadas",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "Full HD",
        popularidade: 8.2
    },
    {
        id: "round6",
        titulo: "Round 6",
        ano: 2021,
        genero: "Suspense",
        tipo: "serie",
        categoria: "suspense",
        poster: "../images/posters/round6.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Centenas de jogadores endividados aceitam um convite estranho para competir em jogos infantis. Por dentro, um prêmio tentador os espera — com riscos mortais.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=CmRR-0XAttY",
        detalhesUrl: "detalhes-round6.html",
        elenco: ["Lee Jung-jae", "Park Hae-soo", "Jung Ho-yeon"],
        duracao: "1 temporada",
        classificacao: "18",
        classificacaoNum: 18,
        qualidade: "4K",
        popularidade: 9.3
    },
    {
        id: "comando-das-criaturas",
        titulo: "Comando das Criaturas",
        ano: 2025,
        genero: "Animação",
        tipo: "serie",
        categoria: "dc",
        poster: "../images/posters/comando-das-criaturas.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Amanda Waller cria uma equipe de operações secretas composta por monstros prisioneiros.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=n6ss-KWghmQ",
        detalhesUrl: "detalhes-comando-das-criaturas.html",
        elenco: ["Frank Grillo", "David Harbour", "Indira Varma"],
        duracao: "1 temporada",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "HD",
        popularidade: 8.8
    },
    {
        id: "it-bem-vindos-a-derry",
        titulo: "It: Bem-vindos a Derry",
        ano: 2025,
        genero: "Terror",
        tipo: "serie",
        categoria: "terror",
        poster: "../images/posters/it-bem-vindos-a-derry.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Uma prequela dos filmes 'It', explorando a história de Pennywise e a cidade amaldiçoada de Derry.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=hdCIZK2zcYw",
        detalhesUrl: "detalhes-it-bem-vindos-a-derry.html",
        elenco: ["Bill Skarsgård", "Taylour Paige"],
        duracao: "1 temporada",
        classificacao: "18",
        classificacaoNum: 18,
        qualidade: "4K",
        popularidade: 9.0
    },
    {
        id: "pacificador",
        titulo: "Pacificador",
        ano: 2022,
        genero: "Ação",
        tipo: "serie",
        categoria: "dc",
        poster: "../images/posters/pacificador.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "A continuação da história do personagem de 'O Esquadrão Suicida', um homem que acredita na paz a qualquer custo.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=WHXq6tfzHK0",
        detalhesUrl: "detalhes-pacificador.html",
        elenco: ["John Cena", "Danielle Brooks", "Freddie Stroma"],
        duracao: "2 temporadas",
        classificacao: "18",
        classificacaoNum: 18,
        qualidade: "4K",
        popularidade: 8.9
    },
    {
        id: "pll",
        titulo: "Pretty Little Liars",
        ano: 2010,
        genero: "Suspense",
        tipo: "serie",
        categoria: "suspense",
        poster: "../images/posters/pll.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Quatro amigas se unem contra um inimigo anônimo que ameaça revelar seus segredos mais sombrios.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        detalhesUrl: "detalhes-pll.html",
        elenco: ["Troian Bellisario", "Ashley Benson", "Lucy Hale"],
        duracao: "7 temporadas",
        classificacao: "14",
        classificacaoNum: 14,
        qualidade: "HD",
        popularidade: 8.4
    },
    {
        id: "se-nao-fosse-voce",
        titulo: "Se Eu Não Tivesse Te Conhecido",
        ano: 2018,
        genero: "Romance",
        tipo: "serie",
        categoria: "romance",
        poster: "../images/posters/se-nao-fosse-voce.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Um homem que perdeu sua família em um acidente viaja para universos paralelos para tentar mudar o destino.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        detalhesUrl: "detalhes-se-nao-fosse-voce.html",
        elenco: ["Pablo Derqui", "Andrea Ros"],
        duracao: "1 temporada",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "HD",
        popularidade: 7.5
    },
    {
        id: "voce",
        titulo: "Você",
        ano: 2018,
        genero: "Suspense",
        tipo: "serie",
        categoria: "suspense",
        poster: "../images/posters/voce.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Um gerente de livraria perigosamente charmoso fica obcecado por uma aspirante a escritora.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=tT273822234",
        detalhesUrl: "detalhes-voce.html",
        elenco: ["Penn Badgley", "Elizabeth Lail"],
        duracao: "4 temporadas",
        classificacao: "18",
        classificacaoNum: 18,
        qualidade: "Full HD",
        popularidade: 9.2
    },

    // --- ANIMES ---
    {
        id: "one-piece",
        titulo: "One Piece",
        ano: 1999,
        genero: "Aventura",
        tipo: "anime",
        categoria: "anime",
        poster: "../images/posters/one-piece.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Monkey D. Luffy e sua tripulação pirata exploram um mundo fantástico de oceanos infinitos e ilhas exóticas em busca do tesouro supremo.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=YC8SLpnxsL4",
        detalhesUrl: "detalhes-one-piece.html",
        elenco: ["Mayumi Tanaka", "Kazuya Nakai", "Akemi Okamura"],
        duracao: "Mais de 1000 episódios",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "Full HD",
        popularidade: 9.0
    },
    {
        id: "naruto",
        titulo: "Naruto",
        ano: 2002,
        genero: "Aventura",
        tipo: "anime",
        categoria: "anime",
        poster: "../images/posters/naruto.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Naruto Uzumaki, um ninja adolescente barulhento, busca reconhecimento e sonha em se tornar o Hokage, o líder de sua vila.",
        videoUrl: "https://playerflixapi.com/serie/46260",
        trailerUrl: "https://www.youtube.com/watch?v=fR28U_Xovk4",
        detalhesUrl: "detalhes-naruto.html",
        elenco: ["Junko Takeuchi", "Chie Nakamura", "Noriaki Sugiyama"],
        duracao: "220 episódios",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "Full HD",
        popularidade: 8.4
    },
    {
        id: "haikyu",
        titulo: "Haikyu!!",
        ano: 2014,
        genero: "Esporte",
        tipo: "anime",
        categoria: "anime",
        poster: "../images/posters/haikyu!!.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Shoyo Hinata, um garoto de baixa estatura, se junta ao time de vôlei da escola para se tornar um grande jogador.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=6QBiUaO3tL8",
        detalhesUrl: "detalhes-haikyu!!.html",
        elenco: ["Ayumu Murase", "Kaito Ishikawa", "Yu Hayashi"],
        duracao: "4 temporadas",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 8.9
    },
    {
        id: "jojo-bizarre-adventure",
        titulo: "Jojo's Bizarre Adventure",
        ano: 2012,
        genero: "Ação",
        tipo: "anime",
        categoria: "anime",
        poster: "../images/posters/jojo-bizarre-adventure.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "A saga da família Joestar e suas batalhas contra forças sobrenaturais através das gerações.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=NyGZT2AgB4s",
        detalhesUrl: "detalhes-jojo-bizarre-adventure.html",
        elenco: ["Daisuke Ono", "Unshō Ishizuka"],
        duracao: "6 partes",
        classificacao: "16",
        classificacaoNum: 16,
        qualidade: "Full HD",
        popularidade: 9.4
    },
    {
        id: "o-incrivel-circo-digital",
        titulo: "O Incrível Circo Digital",
        ano: 2023,
        genero: "Comédia",
        tipo: "anime",
        categoria: "anime",
        poster: "../images/posters/o-incrivel-circo-digital.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Uma mulher fica presa em um mundo digital bizarro junto com outros humanos, todos transformados em personagens de desenho animado.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=ned09SQH23s",
        detalhesUrl: "detalhes-o-incrivel-circo-digital.html",
        elenco: ["Lizzie Freeman", "Alex Rochon"],
        duracao: "1 temporada",
        classificacao: "12",
        classificacaoNum: 12,
        qualidade: "HD",
        popularidade: 9.6
    },
    {
        id: "101-dalmatas",
        titulo: "101 Dálmatas",
        ano: 1961,
        genero: "Aventura",
        tipo: "anime",
        categoria: "disney",
        poster: "../images/posters/101-dalmatas.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Pongo e Prenda devem resgatar seus filhotes dálmatas da vilã Cruella De Vil, que quer transformá-los em casacos de pele.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=RNg7vtbaC3Y",
        detalhesUrl: "detalhes-101-dalmatas.html",
        elenco: ["Rod Taylor", "Cate Bauer"],
        duracao: "1h 19m",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 8.1
    },

    // --- DESENHOS / CARTOON ---
    {
        id: "hora-de-aventura",
        titulo: "Hora de Aventura",
        ano: 2010,
        genero: "Aventura",
        tipo: "anime",
        categoria: "cartoon",
        poster: "../images/posters/hora-de-aventura.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Um garoto humano chamado Finn e seu melhor amigo, o cão mágico Jake, vivem grandes aventuras na Terra de Ooo.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=51laYl7spBI",
        detalhesUrl: "detalhes-hora-de-aventura.html",
        elenco: ["Jeremy Shada", "John DiMaggio"],
        duracao: "10 temporadas",
        classificacao: "10",
        classificacaoNum: 10,
        qualidade: "HD",
        popularidade: 9.3
    },
    {
        id: "apenas-um-show",
        titulo: "Apenas um Show",
        ano: 2010,
        genero: "Comédia",
        tipo: "serie",
        categoria: "cartoon",
        poster: "../images/posters/apenas-um-show.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "As aventuras surreais de dois zeladores, um gaio-azul chamado Mordecai e um guaxinim chamado Rigby.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=FhKIg8O4AWI",
        detalhesUrl: "detalhes-apenas-um-show.html",
        elenco: ["J.G. Quintel", "William Salyers", "Sam Marin"],
        duracao: "8 temporadas",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 8.5
    },
    {
        id: "o-incrivel-mundo-de-gumball",
        titulo: "O Incrível Mundo de Gumball",
        ano: 2011,
        genero: "Comédia",
        tipo: "serie",
        categoria: "cartoon",
        poster: "../images/posters/o-incrivel-mundo-de-gumball.webp",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "As desventuras de Gumball Watterson, um gato azul de 12 anos, e seu irmão adotivo, Darwin, um peixe-dourado.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=On_IHVGEU6E",
        detalhesUrl: "detalhes-o-incrivel-mundo-de-gumball.html",
        elenco: ["Logan Grove", "Kwesi Boakye", "Teresa Gallagher"],
        duracao: "6 temporadas",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 8.7
    },
    {
        id: "steven-universo",
        titulo: "Steven Universo",
        ano: 2013,
        genero: "Fantasia",
        tipo: "serie",
        categoria: "cartoon",
        poster: "../images/posters/steven-universo.jpg",
        banner: "../images/banners/banner-filme.jpg",
        sinopse: "Steven, um garoto meio humano, meio Gem, aprende a usar seus poderes para proteger o mundo com as Crystal Gems.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
        trailerUrl: "https://www.youtube.com/watch?v=On_IHVGEU6E",
        detalhesUrl: "detalhes-steven-universo.html",
        elenco: ["Zach Callison", "Estelle", "Michaela Dietz"],
        duracao: "5 temporadas",
        classificacao: "L",
        classificacaoNum: 0,
        qualidade: "HD",
        popularidade: 8.6
    }
];